name: Build Tarteel APK
on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install Android NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Install cargo-apk
        run: cargo install cargo-apk

      - name: Build APK
        run: cargo apk build --release

      - name: Upload Tarteel APK
        uses: actions/upload-artifact@v4
        with:
          name: Tarteel-App
          path: target/release/apk/*.apk
          
